# Generated by Django 5.0 on 2025-02-24 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autochecker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='class_subject',
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.CharField(max_length=50)),
                ('schedule', models.CharField(max_length=15)),
                ('students_assigned', models.ManyToManyField(limit_choices_to={'role': 'students'}, related_name='student_classes', to=settings.AUTH_USER_MODEL)),
                ('teacher_assigned', models.ForeignKey(limit_choices_to={'role': 'professor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='classroom',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'student'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_activities', to='autochecker.classroom'),
        ),
        migrations.DeleteModel(
            name='Class',
        ),
    ]
