# Generated by Django 5.0 on 2025-02-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autochecker', '0002_remove_activity_class_subject_classroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='test_cases',
            field=models.CharField(max_length=50),
        ),
    ]
