# Generated by Django 5.0 on 2025-02-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autochecker', '0005_alter_activity_classroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='test_cases',
            field=models.CharField(max_length=255),
        ),
    ]
