# Generated by Django 5.0 on 2025-02-25 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autochecker', '0011_submission_professor_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='class_code',
            field=models.CharField(default='CCCCC22BBA', max_length=10),
            preserve_default=False,
        ),
    ]
