# Generated by Django 5.0 on 2025-02-25 14:39

import autochecker.models
import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autochecker', '0013_alter_classroom_class_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='time_limit',
            field=models.DateTimeField(default=autochecker.models.default_time_closed, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='time_open',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 25, 14, 39, 55, 251661, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='students_assigned',
            field=models.ManyToManyField(blank=True, limit_choices_to=autochecker.models.student_filter, related_name='student_classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
