# Generated by Django 4.2.19 on 2025-03-18 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autochecker', '0015_submission_is_submitted_alter_activity_instructions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='className',
            new_name='class_name',
        ),
    ]
