# Generated by Django 4.2.19 on 2025-06-14 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autochecker', '0016_rename_classname_classroom_class_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='is_submitted',
        ),
    ]
