# Generated by Django 4.2.19 on 2025-07-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autochecker', '0018_testsuite'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('practice', 'practice'), ('activity', 'activity')], default='activity', max_length=20),
        ),
    ]
