# Generated by Django 4.2.19 on 2025-08-23 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autochecker', '0019_activity_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='student_id',
            field=models.CharField(default='Student_id', max_length=10),
        ),
    ]
