# Generated by Django 5.0 on 2025-02-24 14:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autochecker', '0003_alter_activity_test_cases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='students_assigned',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'students'}, related_name='student_classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
