# Generated by Django 5.0 on 2025-02-24 14:14

import autochecker.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autochecker', '0004_alter_classroom_students_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_activities', to='autochecker.classroom'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='teacher_assigned',
            field=models.ForeignKey(blank=True, default=1, limit_choices_to=autochecker.models.professor_filter, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classroom',
            name='schedule',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='students_assigned',
            field=models.ManyToManyField(blank=True, limit_choices_to=autochecker.models.student_filter, related_name='student_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='teacher_assigned',
            field=models.ForeignKey(limit_choices_to=autochecker.models.professor_filter, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
