# Generated by Django 5.0 on 2025-02-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autochecker', '0006_alter_activity_test_cases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='instructions',
            field=models.FileField(blank=True, null=True, upload_to='instructions/'),
        ),
    ]
