# Generated by Django 5.0 on 2025-02-25 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autochecker', '0009_alter_submission_submitted_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='test_cases',
            new_name='check50_slug',
        ),
        migrations.AddField(
            model_name='submission',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='max_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
