# Generated by Django 5.0 on 2025-02-25 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autochecker', '0010_rename_test_cases_activity_check50_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='professor_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
