# Generated by Django 5.0 on 2025-02-25 07:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autochecker', '0012_classroom_class_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='class_code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='students_assigned',
            field=models.ManyToManyField(blank=True, related_name='student_classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
