# Generated by Django 5.0 on 2025-02-27 05:33

import autochecker.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autochecker', '0014_alter_activity_time_limit_alter_activity_time_open_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='instructions',
            field=models.FileField(default=django.utils.timezone.now, upload_to='instructions/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='time_open',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_file',
            field=models.FileField(upload_to=autochecker.models.create_dir),
        ),
    ]
